# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Technical Agile Coaching Materials
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Materials and lesson plans that are engaging, interesting, and 
  useful for teaching agile software development skills. 
  Best used in combination with the book "Technical Agile Coaching" by Emily Bache.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: emilybache
github_username:  emilybache

# Build settings
markdown: kramdown
theme: just-the-docs
search_enabled: true
footer_content: "This content is covered by a <a href=\"https://github.com/emilybache/emilybache.github.io/blob/master/LICENSE.md\">CC-BY-SA-4.0 license.</a>"
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
